-- Database: vet_clinic
DROP TABLE public.animals;

CREATE TABLE IF NOT EXISTS public.animals
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100),
    date_of_birth date,
    escape_attempts integer,
    neutered boolean,
    weight_kg numeric(5,2),
    species character varying(100)
);

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.animals
    OWNER to postgres;
