-- Database: vet_clinic
DROP TABLE public.animals;

CREATE TABLE IF NOT EXISTS public.animals
(
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100),
    date_of_birth date,
    escape_attempts integer,
    neutered boolean,
    weight_kg numeric(5,2),
    species character varying(100)
);

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.animals
    OWNER to postgres;

-- Project 3
DROP TABLE public.owners;
create table owners (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, full_name VARCHAR(100), age INT);

DROP TABLE public.species;
create table species (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100));

ALTER TABLE animals ADD PRIMARY KEY (id);

ALTER TABLE animals DROP COLUMN species;

ALTER TABLE animals ADD COLUMN species_id INT;
ALTER TABLE animals ADD CONSTRAINT species_fkey FOREIGN KEY (species_id) REFERENCES species(id);

ALTER TABLE animals ADD COLUMN owner_id INT;
ALTER TABLE animals ADD CONSTRAINT owner_fkey FOREIGN KEY (owner_id) REFERENCES owners(id);


